import type { Metadata } from "next";
import { Hachi_Maru_Pop } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const hachmaru = Hachi_Maru_Pop({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          `min-h-screen min-w-full antialiased bg-gradient-to-b from-yellow-first to-yellow-end flex flex-col overflow-hidden  ${hachmaru.className}`
        )}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
