create table "public"."Users" (
    "id" bigint generated by default as identity not null,
    "Created_at" timestamp with time zone not null default now(),
    "Username" text,
    "Mailaddress" text,
    "UserId" uuid default auth.uid()
);


alter table "public"."Users" enable row level security;

CREATE UNIQUE INDEX "Users_Mailaddress_key" ON public."Users" USING btree ("Mailaddress");

CREATE UNIQUE INDEX "Users_Username_key" ON public."Users" USING btree ("Username");

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (id);

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

alter table "public"."Users" add constraint "Users_Mailaddress_key" UNIQUE using index "Users_Mailaddress_key";

alter table "public"."Users" add constraint "Users_Username_key" UNIQUE using index "Users_Username_key";

alter table "public"."Users" add constraint "public_Users_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Users" validate constraint "public_Users_UserId_fkey";

grant delete on table "public"."Users" to "anon";

grant insert on table "public"."Users" to "anon";

grant references on table "public"."Users" to "anon";

grant select on table "public"."Users" to "anon";

grant trigger on table "public"."Users" to "anon";

grant truncate on table "public"."Users" to "anon";

grant update on table "public"."Users" to "anon";

grant delete on table "public"."Users" to "authenticated";

grant insert on table "public"."Users" to "authenticated";

grant references on table "public"."Users" to "authenticated";

grant select on table "public"."Users" to "authenticated";

grant trigger on table "public"."Users" to "authenticated";

grant truncate on table "public"."Users" to "authenticated";

grant update on table "public"."Users" to "authenticated";

grant delete on table "public"."Users" to "service_role";

grant insert on table "public"."Users" to "service_role";

grant references on table "public"."Users" to "service_role";

grant select on table "public"."Users" to "service_role";

grant trigger on table "public"."Users" to "service_role";

grant truncate on table "public"."Users" to "service_role";

grant update on table "public"."Users" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."Users"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."Users"
as permissive
for select
to public
using (true);



