create table "public"."chatrooms" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "paticipants" uuid[] not null
);


alter table "public"."chatrooms" enable row level security;

create table "public"."friend_relations" (
    "id" bigint generated by default as identity not null,
    "user_id_a" uuid not null,
    "user_id_b" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "last_interacted" timestamp with time zone
);


alter table "public"."friend_relations" enable row level security;

create table "public"."friend_requests" (
    "id" bigint generated by default as identity not null,
    "sender_id" uuid not null,
    "receiver_id" uuid not null,
    "status" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null
);


alter table "public"."friend_requests" enable row level security;

create table "public"."messages" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "room_id" uuid not null default gen_random_uuid(),
    "sender_id" uuid,
    "content" text,
    "read_by" uuid[]
);


alter table "public"."messages" enable row level security;

CREATE UNIQUE INDEX "Users_UserId_key" ON public."Users" USING btree ("UserId");

CREATE UNIQUE INDEX chatrooms_pkey ON public.chatrooms USING btree (id);

CREATE UNIQUE INDEX friend_relations_pkey ON public.friend_relations USING btree (id);

CREATE UNIQUE INDEX friend_requests_pkey ON public.friend_requests USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

alter table "public"."chatrooms" add constraint "chatrooms_pkey" PRIMARY KEY using index "chatrooms_pkey";

alter table "public"."friend_relations" add constraint "friend_relations_pkey" PRIMARY KEY using index "friend_relations_pkey";

alter table "public"."friend_requests" add constraint "friend_requests_pkey" PRIMARY KEY using index "friend_requests_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."Users" add constraint "Users_UserId_key" UNIQUE using index "Users_UserId_key";

alter table "public"."friend_relations" add constraint "public_friend_relations_user_id_a_fkey" FOREIGN KEY (user_id_a) REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."friend_relations" validate constraint "public_friend_relations_user_id_a_fkey";

alter table "public"."friend_relations" add constraint "public_friend_relations_user_id_b_fkey" FOREIGN KEY (user_id_b) REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."friend_relations" validate constraint "public_friend_relations_user_id_b_fkey";

alter table "public"."friend_requests" add constraint "public_friend_requests_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."friend_requests" validate constraint "public_friend_requests_receiver_id_fkey";

alter table "public"."friend_requests" add constraint "public_friend_requests_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."friend_requests" validate constraint "public_friend_requests_sender_id_fkey";

alter table "public"."messages" add constraint "public_messages_room_id_fkey" FOREIGN KEY (room_id) REFERENCES chatrooms(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "public_messages_room_id_fkey";

alter table "public"."messages" add constraint "public_messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "public_messages_sender_id_fkey";

grant delete on table "public"."chatrooms" to "anon";

grant insert on table "public"."chatrooms" to "anon";

grant references on table "public"."chatrooms" to "anon";

grant select on table "public"."chatrooms" to "anon";

grant trigger on table "public"."chatrooms" to "anon";

grant truncate on table "public"."chatrooms" to "anon";

grant update on table "public"."chatrooms" to "anon";

grant delete on table "public"."chatrooms" to "authenticated";

grant insert on table "public"."chatrooms" to "authenticated";

grant references on table "public"."chatrooms" to "authenticated";

grant select on table "public"."chatrooms" to "authenticated";

grant trigger on table "public"."chatrooms" to "authenticated";

grant truncate on table "public"."chatrooms" to "authenticated";

grant update on table "public"."chatrooms" to "authenticated";

grant delete on table "public"."chatrooms" to "service_role";

grant insert on table "public"."chatrooms" to "service_role";

grant references on table "public"."chatrooms" to "service_role";

grant select on table "public"."chatrooms" to "service_role";

grant trigger on table "public"."chatrooms" to "service_role";

grant truncate on table "public"."chatrooms" to "service_role";

grant update on table "public"."chatrooms" to "service_role";

grant delete on table "public"."friend_relations" to "anon";

grant insert on table "public"."friend_relations" to "anon";

grant references on table "public"."friend_relations" to "anon";

grant select on table "public"."friend_relations" to "anon";

grant trigger on table "public"."friend_relations" to "anon";

grant truncate on table "public"."friend_relations" to "anon";

grant update on table "public"."friend_relations" to "anon";

grant delete on table "public"."friend_relations" to "authenticated";

grant insert on table "public"."friend_relations" to "authenticated";

grant references on table "public"."friend_relations" to "authenticated";

grant select on table "public"."friend_relations" to "authenticated";

grant trigger on table "public"."friend_relations" to "authenticated";

grant truncate on table "public"."friend_relations" to "authenticated";

grant update on table "public"."friend_relations" to "authenticated";

grant delete on table "public"."friend_relations" to "service_role";

grant insert on table "public"."friend_relations" to "service_role";

grant references on table "public"."friend_relations" to "service_role";

grant select on table "public"."friend_relations" to "service_role";

grant trigger on table "public"."friend_relations" to "service_role";

grant truncate on table "public"."friend_relations" to "service_role";

grant update on table "public"."friend_relations" to "service_role";

grant delete on table "public"."friend_requests" to "anon";

grant insert on table "public"."friend_requests" to "anon";

grant references on table "public"."friend_requests" to "anon";

grant select on table "public"."friend_requests" to "anon";

grant trigger on table "public"."friend_requests" to "anon";

grant truncate on table "public"."friend_requests" to "anon";

grant update on table "public"."friend_requests" to "anon";

grant delete on table "public"."friend_requests" to "authenticated";

grant insert on table "public"."friend_requests" to "authenticated";

grant references on table "public"."friend_requests" to "authenticated";

grant select on table "public"."friend_requests" to "authenticated";

grant trigger on table "public"."friend_requests" to "authenticated";

grant truncate on table "public"."friend_requests" to "authenticated";

grant update on table "public"."friend_requests" to "authenticated";

grant delete on table "public"."friend_requests" to "service_role";

grant insert on table "public"."friend_requests" to "service_role";

grant references on table "public"."friend_requests" to "service_role";

grant select on table "public"."friend_requests" to "service_role";

grant trigger on table "public"."friend_requests" to "service_role";

grant truncate on table "public"."friend_requests" to "service_role";

grant update on table "public"."friend_requests" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";


